GET http://localhost:8000/movies

###

GET http://localhost:8000/movies/6485dbc9893edc2f536d7706

###

POST http://localhost:8000/movies
Content-Type: application/json

{
    "title": "Star wars",
    "director": "George"
}
###

DELETE http://localhost:8000/movies/6485dc5bf6f9a0bcb85f9eb4

###

PATCH http://localhost:8000/movies/6485dbc9893edc2f536d7706
Content-Type: application/json

{
    "title": "Toy Story 2",
    "director": "My Wife"
}