GET http://localhost:8000/movies

###

GET http://localhost:8000/movies/6485dbc9893edc2f536d7706

###

POST http://localhost:8000/movies
Content-Type: application/json

{
    "title": "Star wars 7",
    "director": "George",
    "genre": "Science Fiction"
}
###

DELETE http://localhost:8000/movies/64869f477c4be5e19048a528

###

PATCH http://localhost:8000/movies/64869f477c4be5e19048a528
Content-Type: application/json

{
    "title": "Toy Story 2",
    "director": "My Wife",
    "genre": "adventure"
}